# Generated by Django 5.2.3 on 2025-06-21 22:35

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="config",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="template",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="DesignRender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template", models.TextField(default="")),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renders",
                        to="designs.design",
                    ),
                ),
            ],
        ),
    ]
