# Generated by Django 5.2.3 on 2025-06-21 23:02

import designs.fields
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0002_design_config_design_template_designrender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="config",
            field=designs.fields.ConfigField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="designrender",
            name="config",
            field=designs.fields.ConfigField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
