# Generated by Django 5.2.3 on 2025-06-22 02:54

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


def copy_config(apps, schema_editor):
    Design = apps.get_model("designs", "Design")
    DesignConfiguration = apps.get_model("designs", "DesignConfiguration")
    for design in Design.objects.all():
        config = getattr(design, "config", None)
        if not config:
            continue
        for name, data in config.items():
            DesignConfiguration.objects.create(
                design=design,
                name=name,
                field_class=data.get("class"),
                field_kwargs=data.get("kwargs", {}),
            )


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0003_use_config_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("field_class", models.CharField(max_length=255)),
                (
                    "field_kwargs",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        blank=True,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="designs.design",
                    ),
                ),
            ],
            options={
                "unique_together": {("design", "name")},
            },
        ),
        migrations.RunPython(copy_config, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="design",
            name="config",
        ),
    ]
